title: Belltown Pizza
author: Belltown Pizza

avatar: /assets/img/btp-avatar-icon.png
description_length: 50
highlighter: rouge
markdown: kramdown
permalink: /:title/
remove-ads: true
round-avatar: true
timezone: America/Los_Angeles
title-img: /assets/img/btp-logo-banner.png
url: https://www.belltownpizza.net
url-pretty: belltownpizza.net

site-css:
  - /assets/css/belltownpizza.css

site-js:
  - "/assets/js/slice.js"

social-network-links:
  email: "info@belltownpizza.net"
  facebook: belltownpizza
  twitter: belltownpizza
  instagram: belltownpizzaseattle
  telephone: +12064412653

navbar-links:
  Beer: beer
  Cocktails: cocktails
  Wine: wine
  Food: menu
  Specials: specials
  Delivery: delivery
  Contact: contact

navbar-col: "#eaeaea"
navbar-text-col: "#404040"
navbar-border-col: "#ddd"
page-col: "#fff"
text-col: "#404040"
link-col: "#000"
hover-col: "#0085a1"
footer-col: "#565656"
footer-text-col: "#fff"
footer-link-col: "#000"

kramdown:
  input: GFM

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      ext-css: "https://fonts.googleapis.com/css?family=Raleway"
      footer-extra: footer-extra.html
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock

remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap
